<div class="{{$containerClass}}">
  @if($isCheck)
    <input
      type="{{$type}}"
      class="{{$inputClass}}"
      value="{{$value}}"
      id="{{$inputId}}"
      name="{{$name}}"/>
  @endif
  @if(isset($label))
    <label
      class="{{$labelClass}}"
      for="{{$inputId}}">
      {{$label}}
    </label>
  @endif
  @if(!$isCheck)
    <input
      type="{{$type}}"
      class="{{$inputClass}}"
      value="{{$value}}"
      placeholder="{{$placeholder}}"
      id="{{$inputId}}"
      name="{{$name}}"/>
  @endif
</div>